saltstack-formulas/template-formula

- template/defaults.yml
- template/file.sls
- template/init.sls
- template/map.jinja
- template/package.sls
- template/service.sls
**Summary** 
- defaults live in defaults.yml
- map jinja overrides by grain + merges pillar:lookup
- split all contextually similar states in their own files
> Propose new-ish formula style

- README.rst
It is always better to use `https` wherever possible.
@aboe76 Please, would you be able to merge this in? Thank you.
> Use https in the link to SaltStack documentation

- CHANGELOG.rst
- VERSION
- template/map.jinja
- template/osfamilymap.yaml
- template/osmap.yaml
Fixed issues with `map.jinja`.  Since this formula is for reference purposes, I've added the other OS values found in other formulas, in both `osfamilymap.yaml` and `osmap.yaml`.
> Fix `map.jinja` and add more OSes

- CHANGELOG.rst
- VERSION
- template/map.jinja
- template/osfingermap.yaml
* map.jinja: use grains.filter_by instead of defaults.merge because defaults.merge does not work with salt-ssh. https://github.com/saltstack/salt/issues/51605
* Added osfingermap.yaml.
* Updated changelog and version. (Also set a tag in my repo, not sure how GitHub handles this.)
>  map.jinja: use grains.filter_by instead of defaults.merge

- .gitignore
- .kitchen.yml
- .travis.yml
- CHANGELOG.rst
- FORMULA
- Gemfile
- pillar.example
- test/integration/default/controls/config_spec.rb
- test/integration/default/controls/packages_spec.rb
- test/integration/default/controls/services_spec.rb
- test/integration/default/inspec.yml
The template can be tested, it's using `pkg: bash` and `service:name: systemd-udevd` in `pillar.example`
> Add a testing scaffold with `kitchen-ci`, `inspec` and `travis` support

- CONTRIBUTING.md
- README.rst
- release-rules.js
- release.config.js
Update due to introduction of `semantic-release` in cbcfd75.
> docs(contributing): add commit message formatting instructions

- .travis.yml
- CONTRIBUTING.md
- commitlint.config.js
* https://github.com/conventional-changelog/commitlint
- Lint commit messages.
- Ensure that they are in accordance with `semantic-release` settings.
- Use Travis CI to display errors and prevent release stage if so.
* https://conventional-changelog.github.io/commitlint/#/reference-rules
- Specific rules are defined in `commitlint.config.js`.
- Using the default rules at the time of this commit.
- This link gives full details on the default values and how to
provide custom settings.
---
Notes follow in comments below.
> ci(travis): include `commitlint` stage

- .travis.yml
- CONTRIBUTING.md
- release.config.js
* https://github.com/gaocegege/maintainer
- The existing `AUTHORS.md` was created manually using this CLI app.
- This commit automates this process to run during the CI build, as part of the overall `semantic-release` process.
* https://github.com/myii/maintainer
- Using an enhanced, forked version of this app.
- The authors are now shown in a table rather than a bulleted list.
---
This PR is effectively complete but I've marked it `WIP` to get some confirmations before merging.  The main issue is the use of the forked version rather than the (unmaintained) upstream version.  To keep things simple, compare the end results for each:
* **Main**: [existing `AUTHORS.md`](https://github.com/saltstack-formulas/template-formula/blob/410acf82a828a9307c28a448d3d6c9a0be3cceee/AUTHORS.md)
* …
> feat(authors): update automatically alongside `semantic-release`

- .travis.yml
- kitchen.yml
- test/integration/default/inspec.yml
Based on discussions Slack/IRC/Matrix leading to [the following plan](https://freenode.logbot.info/saltstack-formulas/20190220#c2012702):
* Debian:
- debian-9
- debian-8
- ubuntu-18
- ubuntu-16
* RedHat:
- centos-7
- centos-6
- fedora
* Suse:
- opensuse
---
WIP because 6/8 are working (the other two have been commented out for now), so need to work out how we want to proceed.
> feat(kitchen+travis): conduct tests on a wider range of platforms

- .travis.yml
- CONTRIBUTING.md
- README.rst
- TOFS_pattern.md
* https://github.com/jonschlinkert/markdown-toc
- Generate a markdown TOC (table of contents) for any markdown files.
---
Our Markdown files are quite lengthy, with content still to be added.  Having a TOC is invaluable but manual maintenance is a pain.  Using the available package linked above, the process of maintaining the TOC across all relevant files is automated during the Travis `semantic-release` run.
> feat(toc): use `markdown-toc` directly to update inline

- template/config.sls
- template/files/default/example.tmpl.jinja
- template/macros.jinja
* As discussed between comments:
- https://freenode.logbot.info/saltstack-formulas/20190214#c1995273
- https://freenode.logbot.info/saltstack-formulas/20190214#c1995487
---
I'll explain this inline and in further comments.
---
* PR is based on the proposed `pillar.example` scheme.
> Improve TOFS implementation for increased configurability

- .travis.yml
- kitchen.yml
* The actual `opensuse/leap` image was passing but not running any
of the `inspec` tests -- it links to version `15.x`
* `salt-minion` is `42.3`
> ci(kitchen): use `salt-minion` version of `opensuse` to ensure tests run

- .travis.yml
* The `release` stage will always fail due to security reasons:
- E.g. https://travis-ci.com/saltstack-formulas/template-formula/jobs/180068519#L466.
- Discussed: https://github.com/saltstack-formulas/template-formula/pull/42#issuecomment-466446324.
* The `release` stage is unnecessary for PRs until the merge to `master`, in any case.
> ci(travis): prevent `release` stage running for PRs

- template/config.sls
- template/install.sls
- template/map.jinja
- template/service.sls
* Close #22.
---
Adapted from the introduction in 068a94d (#28):
https://github.com/saltstack-formulas/template-formula/blob/068a94d3a242ec818640205626b011f8e53acf1a/template/macros.jinja#L46
> refactor(tpldir): use `tpldir` or derivatives to make formula portable

- template/config.sls
* With nested `.sls` files, `tpldir` respectively resolves to:
- `template/<subdir>`
* Without this fix, only the default value provided is ever used, respectively:
- `['example.tmpl', 'example.tmpl.jinja']`
* Follows-on from https://github.com/saltstack-formulas/systemd-formula/pull/22
> fix(tofs): use `tpldir` derivative `topdir` for pillar (config) paths

- .travis.yml
- kitchen.yml
* https://github.com/saltstack/salt/issues/51808
> ci(kitchen+travis): disable `debian-8` due to `2019.2` installation bug

- kitchen.yml
A little update for Kitchen provision_commands to update repository information before installing packages.
I had an old debian-9 container which couldn't install udev. This fixes it.
> ci(kitchen): check for repos updates before trying package installation

- template/map.jinja
- template/osfamilymap.yaml
- template/osfingermap.yaml
- template/osmap.yaml
fixes #59 with a little inline comment in specified files.
The alternative would be to document how to remove unused import from map.jinja, but the doc about 'template-formula use' is still to be done, so I prefer to add this little comment meanwhile.
> docs(yaml): os*.yaml map files needs at least an empty dict

- .travis.yml
- kitchen.yml
* Close #50.
* https://github.com/saltstack/salt/issues/51808
* https://github.com/saltstack/salt-pack/issues/657#issuecomment-467932962
> ci(kitchen+travis): use `debian:jessie-backports` as `debian-8`

- .travis.yml
- docs/CONTRIBUTING.rst
- docs/README.rst
- docs/index.rst
* Convert the existing internal link to use `:ref:` instead
> docs(rtd): use internal link targets at the top of each `.rst` file

- docs/CONTRIBUTING.rst
- docs/README.rst
- docs/TOFS_pattern.rst
- docs/_static/css/custom.css
- docs/index.rst
* Include:
- docs(tofs): use `literalinclude` of `macros.jinja` instead of code dupe
- Fix link texts
- Apply text formatting
- Split some of the long lines (improved diffs)
- Remove extra `\ ` appearing after conversion from Markdown
- Improve ordered (numbered) nested lists
- Use 3-character indents under RST directives
- Use Jinja commenting in Jinja examples (not just `#`)
> docs(contributing): add documentation contribution guidelines

- template/map.jinja
Got reminded of this when sending the fix for https://github.com/saltstack-formulas/redis-formula/pull/77.  Going to merge since this is the most minor change.
> style(map): use `-` for each Jinja block

- kitchen.yml
* https://github.com/saltstack-formulas/packages-formula/pull/50#discussion_r262769817
- `pillars-from-files` is deprecated in favor of `pillars_from_files`
> refactor(kitchen): `pillars-from-files` => `pillars_from_files`

- docs/TOFS_pattern.rst
- pillar.example
- template/config/file.sls
- template/macros.jinja
* As discussed in the Slack/IRC/Matrix room from this point forward:
- https://freenode.logbot.info/saltstack-formulas/20190308#c2046753
---
Once agreed upon, changes need to propagated based on recent TOFS updates in other formulas:
Please add a comment if I have missed anywhere else.
---
Have tested this with a modified `template/config.file.sls`, introducing multiple uses of the `files_switch` macro.  Confirmed that I got the same results before and after these changes:
```sls
template-config-file-file-managed:
file.managed:
- name: /etc/template.d/custom-ubuntu.conf
- source:
- salt://template/files/ABC/example_alt.tmpl
- salt://template/files/Debian/example_alt.tmpl
- salt://template/files/default/example_alt.tmpl
- mode: 644
- user: root
- group: root
- template: jinja …
```
>  fix(tofs): use `source_files` instead of `files`

- docs/TOFS_pattern.rst
* docs/TOFS_pattern.rst: rename “nfs” to “ntp”.
> docs(tofs): incorrect path for “source_files” lookup key

- docs/TOFS_pattern.rst
- template/config/file.sls
- template/macros.jinja
We can hide the call to “salt['config.get']” in the macro by only
asking for a namespace where to lookup the “source_files”.
* docs/TOFS_pattern.rst (Example): document the use of the new
“namespace” parameter.
* template/macros.jinja: add a new “namespace” parameter.
Lookup files override under
“<tplroot>:tofs:sources_files:<namespace>” and fallback to
“source_files” parameter.
* template/config/file.sls (template-config-file-file-managed): use
the new “namespace” parameter
> refactor(tofs): avoid using “salt['config.get']” for formula writers

- Gemfile
* `kitchen-salt 0.0.21` being installed instead of current latest `0.5.0`
- Failing builds since `pillars_from_files` is not recognised
- Deprecated `pillars-from-files` is working but not the right solution
* Reason: `test-kitchen 2.0.0` was released 3 days ago on March 20, 2019
- `kitchen-salt 0.5.0` depends on `test-kitchen ~> 1.4`
- `kitchen-salt 0.0.21` depends on `test-kitchen >= 0`, so gets pulled
* Remove `test-kitchen` since it is pulled automatically by the other gems
- Allow the correct version to be installed via. dependency resolution
---
More detailed explanation on Slack:
> Found the problem: `Fetching kitchen-salt 0.0.21`.
> 
> The working CI runs: `Fetching kitchen-salt 0.5.0`.
> 
> Due to this, `pillars_from_files` is not recognised and reverting to the deprecated …
> fix(travis): use version numbers in Gemfile to prevent failed builds

- .travis.yml
- kitchen.yml
This reverts commit 1b9d2493c94b4dbeb21ea5e9c6596195cf3ce5cc.
* https://github.com/saltstack/salt-pack/issues/657#issuecomment-474954298
- `python-systemd` is now available in the SaltStack repo
* Amended the commit to add: `image: debian:8`
> revert(kitchen+travis): use `debian:jessie-backports` as `debian-8`

- template/libtofs.jinja
Effectively identical to https://github.com/saltstack-formulas/systemd-formula/pull/27, except that (A) has been provided by merged PR #79.
> refactor(tofs): update with latest changes inc. 100% portable `libtofs.jinja`

- .travis.yml
- kitchen.yml
* Based on: https://github.com/saltstack-formulas/salt-formula/pull/406
---
Merged between the existing setup and the new one linked above.  This paves the way for specific testing to be done by salt version, etc.
> ci(kitchen+travis): implement new distro-python-salt_version matrix

- .travis.yml
- kitchen.yml
@javierbertoli has prepared pre-salted images, which run much faster.  This `WIP` PR implements these for CI testing instead.
---
> ci(kitchen): use pre-salted images instead

- template/map.jinja
- template/osfamilymap.yaml
- template/osfingermap.yaml
- template/osmap.yaml
* For all `os*map.yaml` files
* Remove redundant `or {}` from `map.jinja`
* Close #93
---
See main discussion in #93.  Also links back to #59 and #60.
> fix(comments): explain that at least an empty dict is required

- .gitignore
* Alongside commit: 3860bf9
* Quoting from https://kitchen.ci/docs/getting-started/kitchen-yml/:
- As of test-kitchen 1.21.0, we now prefer `kitchen.yml` over `.kitchen.yml`.
- This preference applies to `kitchen.local.yml` as well.
- This is backward compatible so the dot versions continue to work.
> chore(gitignore): add `kitchen.local.yml`

- template/map.jinja
We've had some discussions in Slack/IRC/Matrix about moving on from `pillar.get` to `config.get`.  `libtofs.jinja` is already using the latter.  Selected `WIP` for this PR since this is something to consider across all formulas.  The intention here is to open up the discussion about going forward with this.
CC: @gtmanfred.
> refactor(map): use `config.get` instead of `pillar.get`

- .travis.yml
- kitchen.yml
- test/integration/default/controls/services_spec.rb
- test/integration/default/inspec.yml
* Add `suse` to `inspec.yml` for `opensuse-leap-15`
---
The pre-salted images have been updated, with more combinations available as well as more goodies!  This is the next step towards attaining a `5 x 3` matrix, which would have each `os` represented three times, for each of the supported salt versions.
> ci(kitchen+travis): use latest pre-salted images

- docs/README.rst
If this is merged, the following task becomes active:
> docs(readme): add testing section based on `postgres-formula`

- template/map.jinja
* Fix 5dc0b86 in #95
- No option `merge=True` for `config.get`
* ~Use `pillar.get` for `salt-call` (i.e. `salt-ssh`)~
* ~Use `config.get` via. `defaults.merge` otherwise~
- ~Reintroduce based on 775a930 in #20~
---
Update: The whole method of fixing this changed completely by the [end of this PR](https://github.com/saltstack-formulas/template-formula/pull/102#issuecomment-492684630).
---
Apologies for seeking multiple reviews again but `map.jinja` is the core of our formulas and this is a significant change, merging the map based on the type of minion.  In https://github.com/saltstack-formulas/template-formula/pull/95#issuecomment-488061151, I mentioned that it appeared to be either one or the other:
> 1. Use `config.get` via. `defaults.merge` -- get the benefit but leave `salt-ssh` …
> fix(`map.jinja`): use pillar/config `.get` according to `__cli` option

- template/map.jinja
When updating a formula the following should be sufficient:
```
cp template-formula/template/map.jinja my-formula/my/map.jinja
sed -i '/set template =/set my =/' my-formula/my/map.jinja
```
Tested with `salt` and `salt-ssh` on FreeBSD 11.2.
@myii I'm bringing back a useful change you introduced earlier.
> map.jinja: use tplroot

- pillar.example
- template/config/file.sls
- template/defaults.yaml
- template/files/default/example.tmpl.jinja
- template/map.jinja
- template/osfamilymap.yaml
- test/integration/default/controls/config_spec.rb
The merge which was formerly done by `pillar.get(..., merge=True)` has now to be performed by `grains.filter_by`.
Tested on FreeBSD with both `salt` and `salt-ssh`.
> fix(`map.jinja`): _merge_ defaults and `config.get`

- .travis.yml
* The selected 5 in a "T"-shaped matrix:
```
- 2019.2 (py3): debian-9   fedora-29   opensuse-leap-15
- 2018.3 (py2):           ubuntu-1604
- 2017.7 (py2):             centos6
```
* Covers each `os`, each Salt version and both Python versions
---
I was going to go for `centos-7` and `fedora-28` instead but `centos-6` is a "special" platform, which always throws up interesting situations (including not being `systemd`-based).
> ci(travis): reduce matrix down to 5/6 instances (ref: #118)

- docs/README.rst
* https://github.com/saltstack-formulas/vault-formula/blob/43dc95d/docs/README.rst#requirements
> docs(readme): add testing requirements section (from `vault-formula`)

- test/integration/default/controls/services_spec.rb
* `train` gem has been fixed upstream
- https://github.com/inspec/train/pull/451
- https://rubygems.org/gems/train/versions/2.1.7
> test(`services_spec`): remove temporary `suse` conditional

- template/libtofs.jinja
* To prevent path breakage when any of the following settings are used
in the pillar/config:
```yaml
tofs:
path_prefix: ''
dirs:
files:     ''
default:   ''
```
---
This PR is based on some discussions in our Slack/IRC/Matrix room, where @sticky-note has been looking at how TOFS can be introduced to  the `nginx-formula` (leading to https://github.com/saltstack-formulas/nginx-formula/pull/238).  The above pillar was set and led to some breakages, which I will cover in subsequent comments in this PR.
---
Edit by @n-rodriguez: the diff is in the double slash `//` before and after. Great job :+1:
> fix(`libtofs`): use `select` to deal with empty strings in path

- template/config/file.sls
- template/osfamilymap.yaml
This PR is a basic, but not ideal, enhancement for MacOS.
- There is no 'root' group on Darwin
- There is no `user` and `group` grains either (pity).
- The directory `/etc/template` is not created by homebrewed package installs
> feat(MacOS): Basic package and group handling

- template/osfamilymap.yaml
> refactor(`osfamilymap`): avoid *BSD ambiguity with MacOS `rootgroup`

- pillar.example
- template/defaults.yaml
- template/osfamilymap.yaml
- template/osfingermap.yaml
- template/osmap.yaml
- template/package/clean.sls
- template/package/install.sls
- test/integration/default/controls/config_spec.rb
prometheus on centos needs a [repo](https://github.com/lest/prometheus-rpm#centos-7) setup.  I've studied how best to incorporate this into this formula and the result is [here](https://github.com/saltstack-formulas/cloudfoundry-formula/tree/master/cloudfoundry/cli/package). My method involved introducing a **pkg** dictionary to collect packaging related details. That provided the model on which to propose handling package repos. The problem is that "pkg" variable is already in use.  
```
pkg: template
```
This PR is to reclaim "pkg" variable as dict. Let me know if you like the approach. 
```
pkg:
name: template
use_upstream_repo: True
use_upstream_archive: False
archive: {}
repo:
managed: {}
```
The followup PR will be to to add repo support to both template and then prometheus …
> refactor(naming): reserve 'pkg' as name of packaging dict

- test/integration/default/README.md
- test/integration/default/inspec.yml
Update default inspec profile structure per guidelines.
> README.md should be used to explain the profile, its scope, and usage
> Use platform-name to restrict on a specific platform name. ... For compatibility we support os-name and os-family. We recommend all users to change os-name to platform-name and os-family to platform-family.
We will see if unit tests pass ;-)
> test(inspec): readme for default profile and a fix

- FORMULA
- test/integration/default/controls/config_spec.rb
- test/integration/default/controls/packages_spec.rb
- test/integration/default/controls/services_spec.rb
- test/integration/default/inspec.yml
For consistency rename "Template" to "template". 
Related to #98
> refactor(string): remove capitalisation from 'template' string

- docs/TOFS_pattern.rst
- pillar.example
- template/config/file.sls
- template/libtofs.jinja
* https://github.com/saltstack-formulas/nginx-formula/pull/247#issuecomment-514262549
- The main issue is that the `nginx-formula` has dynamic values being used as the default `source_files` -- there is no way to provide this from the pillar/config in a sensible fashion
- Prepending to this default (rather than overriding it) resolves this problem entirely, without adding excessive entries to the `source`
* Closes #151
---
CC: @baby-gnu.
> fix(tofs): prepend the config-based `source_files` to the default

- docs/CONTRIBUTING.rst
* Automated using `ssf-formula` (v0.1.0-rc.4)
> chore: use `semantic-release` cross-formula standard structure

- FORMULA
* When formula conversions are performed, this line is usually unchanged
* This ensures that these conversions aren't using even older versions by default
---
Noticed this when reviewing https://github.com/saltstack-formulas/dhcpd-formula/pull/31.
> fix(formula): update to current oldest supported version of Salt

- docs/TOFS_pattern.rst
- template/libtofs.jinja
- template/subcomponent/config/file.sls
So there are two TOFS improvements here in two commits.
For the first one:
* Only the `systemd-formula` uses these, so avoid for all other formulas
- So need to merge this before propagating https://github.com/myii/ssf-formula/pull/3
The second commit (refactor(libtofs): remove deprecated `v1_path_prefix` argument):
* Unused throughout all SaltStack Formulas
- Effectively superseded by using subpath
- May as well merge this and have this propagated by https://github.com/myii/ssf-formula/pull/3 as well
> fix(libtofs): avoid using subpath by default

- .travis.yml
- .yamllint
- kitchen.yml
- template/map.jinja
- template/osfamilymap.yaml
- test/integration/default/inspec.yml
- test/salt/pillar/centos6.sls
- test/salt/pillar/define_roles.sls
* Semi-automated using `ssf-formula` (v0.5.0)
* Fix errors shown below:
```bash
template-formula$ $(grep "\- yamllint" .travis.yml | sed -e "s:^\s\+-\s\(.*\):\1:")
./test/integration/default/inspec.yml
1:1       warning  missing document start "---"  (document-start)
./template/osfamilymap.yaml
1:89      error    line too long (116 > 88 characters)  (line-length)
1:24      error    trailing spaces  (trailing-spaces)
13:2      error    syntax error: found character '%' that cannot start any token
pillar.example
14:4      error    syntax error: found character '%' that cannot start any token
```
---
I've been testing out using `yamllint` on our formulas, centralising the changes using the `ssf-formula`.  I've added this to the `commitlint` stage, to make it an overall `lint` stage instead. …
> feat(yamllint): include for this repo and apply rules throughout

- .travis.yml
- docs/CONTRIBUTING.rst
- kitchen.yml
* Automated using https://github.com/myii/ssf-formula/pull/22
* Also:
- https://github.com/myii/ssf-formula/pull/21
---
The [Ubuntu Bionic 18.04](https://docs.travis-ci.com/user/reference/bionic/) build environment is available for Travis CI.  Our current usage patterns are based on [Ubuntu Xenial 16.04](https://docs.travis-ci.com/user/reference/linux).  The plan here is to prefer the latest build environments available and spread this throughout our (`semantic-release`) formulas.
I've actually already run this across the formulas based on the link above.  This has thrown up an ongoing problem that would be really good to solve at the same time: `opensuse-leap-15` regularly fails in almost half of the formulas and always with the same error:
* `SCP did not finish successfully (): …
> ci: use `dist: bionic` & apply `opensuse-leap-15` SCP error workaround

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Notes:
* Related issues:
- #70 
- https://github.com/saltstack-formulas/exim-formula/issues/8
* Prepared using:
- Upstream `salt` issue template
- Basic template suggested by GitHub
---
The plan is to use across all formulas, if approved.
> docs(issues): provide `Bug report` & `Feature request` templates

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
* Useful to have this provided in a bug report, e.g.
- https://github.com/saltstack-formulas/postfix-formula/issues/100
---
The linked example is one of the first bug reports using the new template.  The template is using level 4 headings at the current time.  Should these all be increased to level 3?  If so, I can attach that to this PR, along with the same change to the feature request template.
> docs(bug_report): add section requesting commit hash / release tag

- .travis.yml
* Automated using https://github.com/myii/ssf-formula/pull/100
---
As discussed, setting up a PR here before propagating to all of the `semantic-release` formulas.  This one is to finalise using the new Travis beta feature (build config validation) after being informed about the final part of the jigsaw here:
* https://github.com/travis-ci/dpl/issues/1138#issuecomment-554988130
I've already confirmed this is working by pushing this to the `apache-formula`:
* https://travis-ci.com/saltstack-formulas/apache-formula/builds/137005150
Notice that `View config` no longer shows any errors or warnings:
* https://travis-ci.com/saltstack-formulas/apache-formula/builds/137005150/config
> [ssf] ci(travis): opt-in to `dpl v2` to complete build config validation [skip ci]

- .travis.yml
- pre-commit_semantic-release.sh
* Automated using https://github.com/myii/ssf-formula/pull/106
---
To be propagated across all formulas using the `ssf-formula`.  According to our discussions, this only requires _one approval_, since it's only CI-based changes.
Idea started from here:
* https://github.com/saltstack-formulas/template-formula/pull/180#issuecomment-558612422
As `shellcheck` is already integrated into Travis, this is easy to run and asides from here, already tested elsewhere:
* https://travis-ci.com/saltstack-formulas/fail2ban-formula/jobs/260717687#L215-L216
* https://travis-ci.org/myii/ssf-formula/builds/617730995#L206-L207
An example of failures (`shellcheck` has excellent error descriptions):
* https://travis-ci.org/myii/ssf-formula/builds/617359726#L206-L367
> [ssf] ci(travis): run `shellcheck` during lint job

- .travis.yml
- kitchen.yml
---
No.
1. Automated using https://github.com/myii/ssf-formula/pull/124
1. https://travis-ci.org/myii/template-formula/builds/645908860 (before)
1. https://github.com/saltstack/salt-bootstrap/pull/1424#issuecomment-581997903
1. https://travis-ci.org/myii/template-formula/builds/646343672 (after)
1. https://github.com/netmanagers/salt-image-builder/pull/21
There have been a number of changes to the `salt-bootstrap` recently in preparation for `Neon`.  One of the side-effects is that attempting to bootstrap the pre-salted `master` images is resulting in failure [2].  The explanation of this is available in that PR's discussion [3].  This PR addresses that by removing the bootstrap for the `master` images [4] and for this to be spread through the 60+ formulas that are currently managed [1]. …
> [ssf] ci(kitchen): avoid using bootstrap for `master` instances

- .rubocop.yml
---
No.
rubocop-hq/rubocop#7542
Upstream RuboCop have moved the `LineLength` cop from the `Metrics` department to the `Layout` department. Although the  current setting still works, running RuboCop results in a warning, and we must assume that the `Metrics/LineLength` setting will be deprecated at some point.
Get rid of this warning message:
[`.rubocop.yml: Metrics/LineLength has the wrong namespace - should be Layout`](https://travis-ci.com/saltstack-formulas/template-formula/jobs/283770413#L307)
> chore(rubocop): move `LineLength` cop from `Metrics` to `Layout`

- TEMPLATE/libtofs.jinja
---
No.
This fix was exposed by #186 and must be merged before it.
`files_switch` mess up the variable exported by `map.jinja`
- `map.jinja` export a variable name as `<tplroot>`
- import of `libtofs.jinja` is done with context and has access to `<tplroot>` variable
- in `files_switch`, appending the empty string to the `fsl` variable modify globally `<tplroot>['tofs']['files_switch']`
* `TEMPLATE/libtofs.jinja`: initialise `fsl` with a copy of `files_switch_list` instead of a reference.
> fix(libtofs): “files_switch” mess up the variable exported by “map.jinja”

- TEMPLATE/libsaltcli.jinja
* To distinguish between:
- `salt-minion`
- `salt-call`
- `salt-ssh`
* Invoked like `map.jinja`:
- `{%- from tplroot ~ "/libsaltcli.jinja" import cli with context %}`
* Based upon work done in PRs: #102, #114 & #115
> chore(`libsaltcli`): add lib to check type of Salt command being used

- docs/README.rst
This PR makes the table of contents less verbose (depth: 1).
```
Table of Contents
General notes
Contributing to this repo
Available states
Testing
```
The default depth (two) is too verbose for users.  
The list of available states is not impacted by this update.
> docs(readme): show only one level in table of contents

- commitlint.config.js
---
No.
Fix header length at 72 chars as agreed at WG meeting. Fix body/header length to 88.
Upstream configuration (`@config-conventional`) has changed in this regard.
> fix(commitlint): fix header length at 72 chars as agreed

- .travis.yml
- TEMPLATE/map.jinja
- bin/convert-formula.sh
- docs/README.rst
- test/integration/default/controls/config_spec.rb
- test/integration/default/inspec.yml
---
No.
Allow '-' and '_' in formula names. Formulas already exist with '-' in the name (prior to `-formula`),
so it seems reasonable to allow creation of new ones.
> fix(convert-formulas.sh): add -_ to allowed chars in formula name

- TEMPLATE/_mapdata/_mapdata.jinja
- TEMPLATE/_mapdata/init.sls
- bin/convert-formula.sh
- test/integration/default/controls/_mapdata_spec.rb
- test/integration/default/files/_mapdata/amazonlinux-1.yaml
- test/integration/default/files/_mapdata/amazonlinux-2.yaml
- test/integration/default/files/_mapdata/arch-base-latest.yaml
- test/integration/default/files/_mapdata/centos-6.yaml
- test/integration/default/files/_mapdata/centos-7.yaml
- test/integration/default/files/_mapdata/centos-8.yaml
- test/integration/default/files/_mapdata/debian-10.yaml
- test/integration/default/files/_mapdata/debian-9.yaml
- test/integration/default/files/_mapdata/fedora-31.yaml
- test/integration/default/files/_mapdata/fedora-32.yaml
- test/integration/default/files/_mapdata/gentoo-2-sysd.yaml
- test/integration/default/files/_mapdata/gentoo-2-sysv.yaml
- test/integration/default/files/_mapdata/opensuse-15.yaml
- test/integration/default/files/_mapdata/oraclelinux-7.yaml
- test/integration/default/files/_mapdata/oraclelinux-8.yaml
- test/integration/default/files/_mapdata/ubuntu-16.yaml
- test/integration/default/files/_mapdata/ubuntu-18.yaml
- test/integration/default/files/_mapdata/ubuntu-20.yaml
---
No.
* Semi-automated using https://github.com/myii/ssf-formula/pull/284
> refactor(map): use top-level `values:` key in `map.jinja` dumps

- CODEOWNERS
- test/integration/default/controls/_mapdata.rb
- test/integration/default/controls/config.rb
- test/integration/default/controls/packages.rb
- test/integration/default/controls/services.rb
- test/integration/default/controls/subcomponent_config.rb
---
No.
I don't find a reference best practices in the documentation but:
- the `_spec` in the control file name is inherited from RSpec and few examples use it
- the `control` name should be an identifier, I matched the `tpldot` name
- the `title` is a human readable description of the `control`
Now the output looks like this:
```
✔  TEMPLATE.config.file: verify the template-formula.conf lines
✔  File /etc/template-formula.conf is expected to be file
✔  File /etc/template-formula.conf is expected to be owned by "root"
[…]	 	 
✔  TEMPLATE.subcomponent.config.file: verify the subcomponent configuration file
✔  File /etc/TEMPLATE-subcomponent-formula.conf is expected to be file
✔  File /etc/TEMPLATE-subcomponent-formula.conf is expected to be owned by "root"
[…]
✔  TEMPLATE._mapdata: …
```
> style(inspec): match current practices for file and control names

- TEMPLATE/libmapstack.jinja
---
No.
If result of the lookup is a number, then map.jinja fails with `TypeError: object of type 'int' has no len()` here
https://github.com/saltstack-formulas/template-formula/blob/080fdcd9f136f19d2a7dd15b17bf4de5c1c4a3c8/TEMPLATE/libmapstack.jinja#L184
If result of the lookup is a list of numbers, then map.jinja fails with `Jinja variable 'int object' has no attribute 'rpartition'` here
https://github.com/saltstack-formulas/template-formula/blob/080fdcd9f136f19d2a7dd15b17bf4de5c1c4a3c8/TEMPLATE/libmapstack.jinja#L202
In this PR I tried to allow it to be numbers, booleans, list of numbers.
Usecases are:
* Uyuni or SUSE Manager exposes its groups as pillar value `group_ids` which is a list of integers: https://www.uyuni-project.org/uyuni-docs/en/uyuni/specialized-guides/salt/salt-custom-s …
> fix(libmapstack): allow mapping by booleans and numbers

- TEMPLATE/libmatchers.jinja
---
No.
When I first looked at `map.jinja` I was having trouble to understand what is `Y`, because I wasn't able to find anything about it in the source code of libmapstack/libmatchers and comments didn't help. After I read the code, I understood that it doesn't matter what character to use as long as it's not `C/G/I`, but `map.jinja` uses `Y`, documentation uses `Y`, so maybe change it also in the comments?
> refactor(libmatchers): match default type with docs

- .gitlab-ci.yml
---
No.
The `test_conversion` job failed during the weekly testing:
* https://gitlab.com/myii/template-formula/-/jobs/2371193438
The `stderr` being:
```
/root/.cache/pre-commit/repomigj3p4n/node_env-default/bin/node:
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found
(required by /root/.cache/pre-commit/repomigj3p4n/node_env-default/bin/node)
```
The following references led to this resolution:
* https://github.com/pre-commit/pre-commit/issues/2351
* https://stackoverflow.com/questions/71939099/bitbucket-pipeline-error-installing-pre-commit-ts-lint
As mentioned there:
> a few days ago node 18.x was released and the prebuilt binaries
> require a relatively-recent version of glibc
Which obviously isn't available on our current Bionic-based `dind` image,
i.e. …
> ci(gitlab-ci): use Node `16.x` for `pre-commit` in test conversion job

- .pre-commit-config.yaml
---
chore/Fix - This addresses an issue with running install-hooks in the repo. 
```
An unexpected error has occurred: CalledProcessError: command: ('/home/user/.cache/pre-commit/repom9h0zugn/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
Processing /home/user/.cache/pre-commit/repom9h0zugn
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'error'
stderr:
error: subprocess-exited-with-error
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [1 lines of output]
error in salt-lint setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '>=3.6.*'
[end of output]
note: This error originates from a subprocess, and is likely not a …
```
> chore: broken install-hooks due to saltlint v0.8.0

- .pre-commit-config.yaml
- .yamllint
---
No.
Switch to using `pre-commit`'s built-in file filtering (a long needed change)
* only run `yamllint` when relevant files have changed
* avoids having to exclude files/dirs not tracked by Git e.g. .kitchen/, .bundle/ etc.
* avoids a `yamllint` bug whereby pillar files under `test/` were not checked due to a conflicting `ignore` entry
Tested by comparing a list files that `yamllint` checks using `--list-files` before and after the change
> test(pre-commit): switch to using `pre-commit`'s built-in file filtering

- .gitlab-ci.yml
- **ci: update `ci-commitlint` to v1.1.76**
- **ci: update `ci-docker-python-ruby` to v2.2.45**
> ci: update CI images for 2025-W09

- commitlint.config.js
* as we need to limit commit message lengths and have limited control over
this in Renovate
> chore: exclude Renovate commits from linting

- .gitlab-ci.yml
- kitchen.yml
* `py3` is not meaningful at the moment as there is no sign of a Python 4
and with `onedir` the version of Python used is not really of concern to
the user
> ci(gitlab-ci): remove `py3` from instance names

- .github/renovate.json5
* the intention is to manually keep Gemfile updated in line
with the latest release of Chef Workstation
> ci(renovate): disable Bundler (Ruby Gems) updates

- .github/workflows/main.yml
- .gitlab-ci.yml
- pre-commit_semantic-release.sh
- release.config.js
- **feat(workflows): dry-run `semantic-release` in GitHub Actions**
- **ci(gitlab-ci): switch to image `techneg/ci-semantic-release`**
- **ci(gitlab-ci): remove deprecated keyword `only` for stage `release**
- **ci: use upstream `maintainer` with new `ignore` option**
- **ci(semantic-release): use `m2r` built in to image**
- **ci(semantic-release): defer to default `branches` values**
- **ci(semantic-release): config option no longer works**
> ci: move towards releasing using GitHub Actions

- .github/workflows/main.yml
* as we have a couple of large hooks which need to be
cached regularly (`renovatebot`)
> ci(workflows): increase `pre-commit` timeout to 10 minutes
