saltstack-formulas/template-formula

- template/map.jinja
Seems nitpicky but I always forget to delete it and it makes for ugly red in gerrit code review. :-)
> Remove whitespace in map.jinja comment

- README.rst
Port changes from saltstack/salt#46214.
@javierbertoli Would you be able to merge this? Thanks!
> Align with SaltStack official formulas doc page

- README.rst
Introduce the concept of formula versioning already described in [SaltStack documentation](https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#versioning)
> Note about formula versioning

- VERSION
Add VERSION file to repository structure according to [SaltStack documentation](https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#repository-structure)
> Add VERSION file

- CHANGELOG.rst
- FORMULA
- VERSION
- template/osfamilymap.yaml
- template/osfingermap.yaml
- template/osmap.yaml
As agreed in the discussion [from this point forward](https://freenode.logbot.info/saltstack-formulas/20190213#c1993658).
> Replace obsolete `VERSION` file and replace with `FORMULA` file

- .gitchangelog.rc
- CHANGELOG.rst
- README.rst
add gitchangelog.rc file for use with gitchangelog and updated the CHANGELOG.rst
> add changelog generator

- CHANGELOG.rst
- README.rst
fix typo and update changelog.
> Fix readme

- CONTRIBUTING.md
* Explain that is should be formatted as a paragraph.
* Show an example of how to supply it.
> docs(contributing): separate `BREAKING CHANGE` under its own heading

- TOFS_pattern.md
- pillar.example
- template/macros.jinja
* Close #44.
---
Essentially, this is completing the remaining task from #28.
> TOFSv2: Update all documentation and inline comments as required

- .travis.yml
- kitchen.yml
- pillar.example
- test/integration/default/controls/packages_spec.rb
- test/integration/default/controls/services_spec.rb
* Close #104
---
This is an example of how #104 could be resolved, using `crond` as suggested by @javierbertoli, while making use of the `*.yaml` files as suggested by @baby-gnu.  This allows discussions to begin about how to finalise this implementation.
> feat(centos-6): reshape formula and tests for this platform

- docs/README.rst
Continues #112 (CC: @n-rodriguez).
> docs(readme): tidy headings

- .gitignore
- .travis.yml
- kitchen.yml
- test/integration/default/README.md
- test/integration/default/inspec.yml
* Automated using `ssf-formula` (v0.1.0-rc.3)
> chore: use `semantic-release` cross-formula standard structure

- docs/CONTRIBUTING.rst
* Automated using:
- https://github.com/myii/ssf-formula/pull/30
- https://github.com/myii/ssf-formula/pull/32
- https://github.com/myii/ssf-formula/pull/37
- https://github.com/myii/ssf-formula/pull/39
> docs(contributing): add recent `semantic-release` formulas

- bin/convert-formula.sh
---
No.
* https://github.com/saltstack-formulas/template-formula/pull/180#discussion_r357308821
* https://github.com/saltstack-formulas/template-formula/pull/180#discussion_r357318860
* https://github.com/saltstack-formulas/template-formula/pull/180#discussion_r357362707
> fix(convert-formula.sh): apply remaining suggestions from #180

- .rubocop.yml
- .travis.yml
- bin/convert-formula.sh
- docs/README.rst
---
No.
Further improvements based on comments in [#180](https://github.com/saltstack-formulas/template-formula/pull/180#issuecomment-565334227), including an usage guide and removal of elements not needed in a derivative formula.
> Improve reusability

- FORMULA
- TEMPLATE/osfingermap.yaml
- TEMPLATE/osmap.yaml
---
No.
Realised that there was an erroneous entry in `osfingermap.yaml` here:
* https://github.com/saltstack-formulas/openldap-formula/pull/24#discussion_r371062614
Added the rest of the OS details from our current supported CI platforms, to prevent having to look up the values each time from elsewhere.
As-is.
N/a.
> fix: fix `CentOS Linux-7` and add `os` details from current CI setup

- .gitignore
---
No.
The directory `.bundle` is created e.g. when the command `bundle install --with=vagrant` is run.
Prevent Git from trying to track this directory.
> chore(git): add Bundler config dir to `.gitignore`

- pillar.example
- test/integration/default/controls/services_spec.rb
---
No.
* The latter is not available on the stripped down pre-salted images
(for Debian and Ubuntu).
- https://travis-ci.org/github/myii/template-formula/builds/665530602
> refactor(service): use `systemd-journald` instead of `systemd-udevd`

- TEMPLATE/service/running.sls
---
No.
As shown in the description below.
* Service isn't restarted if the config file changes
* Made aware of this in the `keepalived-formula`, which was updated to
this `template-formula` structure
- https://github.com/saltstack-formulas/keepalived-formula/issues/37
- https://github.com/saltstack-formulas/keepalived-formula/pull/41
* May need to reconsider: should we really be watching the whole `sls`
rather than explictly watching each state?
> fix(running.sls): use `watch` not `require` to ensure service restart

- .travis.yml
- bin/convert-formula.sh
---
No.
Fixes #192
Use portable `sed` function to make text replacements.
> fix(convert-formula.sh): use portable `sed` function to make replacements

- CODEOWNERS
* Automated using https://github.com/myii/ssf-formula/pull/173
---
No.
As discussed in the last couple of working group meetings, here's the `CODEOWNERS` file I'm proposing to use across the repos.  It's being managed by the `ssf-formula` and I've already conducted a lot of tests with issues surrounding it, such as repo permissions required, separate sections for `semantic-release`, etc.  Here are a couple of `CODEOWNERS` files which are already out there:
* [`libvirt-formula`](https://github.com/saltstack-formulas/libvirt-formula/blob/e8760b7f47c507182f7235b2d3d94e4f95f0ee1b/CODEOWNERS)
* [`salt-formula`](https://github.com/saltstack-formulas/salt-formula/blob/3a46ca426b15c64c507b78d37782c45ff02c75a8/CODEOWNERS)
When no global owner is defined (which will be most of the formulas for …
> chore(codeowners): add to repo [skip ci]

- bin/convert-formula.sh
- docs/README.rst
---
No.
A consequence of #197
We do not want the Formulas working group to be owners of all new formulas generated from this template, therefore: on template conversion, unassign @saltstack-formulas/wg as whole-formula code owners.
Assign `@NONE` instead. (The user `NONE` does not exist and, at least, currently cannot be created)
NA
```
--- a/CODEOWNERS
+++ b/CODEOWNERS
@@ -2,7 +2,7 @@
-*                                           @saltstack-formulas/wg
+*                                           @NONE
```
> feat(convert-formula.sh): assign `@NONE` as whole-formula owner

- .pre-commit-config.yaml
- .rstcheck.cfg
- .travis.yml
- bin/install-hooks
- docs/CHANGELOG.rst
- docs/CONTRIBUTING_DOCS.rst
- docs/README.rst
- docs/_static/css/custom.css
---
No.
Add configuration for [`pre-commit`](https://pre-commit.com/) to allow automatic linting, some syntax checking, whitespace fixing and checking for a valid commit message prior to a successful `git commit`.
Replicates the current linting etc. run in Travis CI.
NA
```
$ cat TEMPLATE/files/default/example.tmpl
########################################################################
########################################################################
{{ source}}
This is an example file from SaltStack template-formula.
$ git add TEMPLATE/files/default/example.tmpl
$ pre-commit run
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Ruby style with rubocop and …
```
> chore: add optional `pre-commit` configuration

- TEMPLATE/_mapdata/_mapdata.jinja
- TEMPLATE/_mapdata/init.sls
- kitchen.yml
- test/integration/default/controls/_mapdata_spec.rb
- test/integration/default/controls/packages_spec.rb
- test/integration/default/controls/services_spec.rb
- test/integration/default/files/_mapdata/amazonlinux-1.yaml
- test/integration/default/files/_mapdata/amazonlinux-2.yaml
- test/integration/default/files/_mapdata/arch-base-latest.yaml
- test/integration/default/files/_mapdata/centos-6.yaml
- test/integration/default/files/_mapdata/centos-7.yaml
- test/integration/default/files/_mapdata/centos-8.yaml
- test/integration/default/files/_mapdata/debian-10.yaml
- test/integration/default/files/_mapdata/debian-9.yaml
- test/integration/default/files/_mapdata/fedora-31.yaml
- test/integration/default/files/_mapdata/fedora-32.yaml
- test/integration/default/files/_mapdata/opensuse-15.yaml
- test/integration/default/files/_mapdata/ubuntu-16.yaml
- test/integration/default/files/_mapdata/ubuntu-18.yaml
- test/integration/default/files/_mapdata/ubuntu-20.yaml
- test/integration/default/inspec.yml
- test/integration/share/README.md
- test/integration/share/inspec.yml
- test/integration/share/libraries/system.rb
---
No.
Verify `map.jinja` dump using `_mapdata` state.
> test(map): verify `map.jinja` dump using `_mapdata` state

- .travis.yml
- FORMULA
- kitchen.yml
- test/integration/default/controls/_mapdata_spec.rb
- test/integration/default/files/_mapdata/oracle-7.yaml
- test/integration/default/files/_mapdata/oracle-8.yaml
- test/integration/default/inspec.yml
- test/integration/share/README.md
- test/integration/share/inspec.yml
- test/integration/share/libraries/system.rb
---
No.
* Automated using https://github.com/myii/ssf-formula/pull/258 (main commit).
* https://github.com/saltstack-formulas/openssh-formula/pull/195
1. Update to use the new pre-salted Tiamat images as part of the agreed changes to the CI matrix across all formulas.
1. Deprecate `2019.2` except for the existing images used by the `upstart` suite.
1. Remove unnecessary hostname mangling, as implemented in the `openssh-formula`.
1. Add testing for Oracle Linux.
As-is.
As shown in Travis.
> ci(kitchen+travis): use `tiamat` pre-salted images

- .travis.yml
- TEMPLATE/osfamilymap.yaml
- kitchen.yml
- test/integration/default/files/_mapdata/gentoo-2-sysd.yaml
- test/integration/default/files/_mapdata/gentoo-2-sysv.yaml
- test/integration/default/inspec.yml
- test/integration/share/inspec.yml
- test/integration/share/libraries/system.rb
- test/salt/pillar/gentoo.sls
---
No.
* Semi-automated using https://github.com/myii/ssf-formula/pull/268
Make use of the new pre-salted images:
* https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/merge_requests/55
> feat: add Gentoo support

- test/integration/share/libraries/system.rb
---
No.
This fix the rubocop error:
```
test/integration/share/libraries/system.rb:12:3: W: Lint/MissingSuper: Call super to initialize state of the parent class.
def initialize ...
^^^^^^^^^^^^^^
```
> test(inspec): `system.rb` must call parent class initialisation

- CODEOWNERS
---
No.
ensure `lib*` files are owned by `ssf` across new formulas (h/t @myii )
> fix(codeowners): ensure `lib*` files are owned by `ssf`

- TEMPLATE/_mapdata/init.sls
- test/integration/default/files/_mapdata/amazonlinux-1.yaml
- test/integration/default/files/_mapdata/amazonlinux-2.yaml
- test/integration/default/files/_mapdata/arch-base-latest.yaml
- test/integration/default/files/_mapdata/centos-6.yaml
- test/integration/default/files/_mapdata/centos-7.yaml
- test/integration/default/files/_mapdata/centos-8.yaml
- test/integration/default/files/_mapdata/debian-10.yaml
- test/integration/default/files/_mapdata/debian-9.yaml
- test/integration/default/files/_mapdata/fedora-31.yaml
- test/integration/default/files/_mapdata/fedora-32.yaml
- test/integration/default/files/_mapdata/gentoo-2-sysd.yaml
- test/integration/default/files/_mapdata/gentoo-2-sysv.yaml
- test/integration/default/files/_mapdata/opensuse-15.yaml
- test/integration/default/files/_mapdata/oraclelinux-7.yaml
- test/integration/default/files/_mapdata/oraclelinux-8.yaml
- test/integration/default/files/_mapdata/ubuntu-16.yaml
- test/integration/default/files/_mapdata/ubuntu-18.yaml
- test/integration/default/files/_mapdata/ubuntu-20.yaml
---
No.
* Semi-automated using https://github.com/myii/ssf-formula/pull/287
> fix(_mapdata): ensure map data is directly under `values`

- .gitignore
---
No.
For Visual Code/Studio.
> chore(git): add visual studio to gitignore

- .pre-commit-config.yaml
---
No.
Fixes #226
* new hook follows upstream versions more closely, and manages the
binary dependency
> chore(shellcheck): switch hook for `shellcheck`

- test/integration/default/controls/_mapdata.rb
---
No.
Automatically rename the `_mapdata` control when using `bin/convert-formula.sh`.
* test/integration/default/controls/_mapdata.rb: use `TEMPLATE` to let `conver-formula.sh` automatically rename the control.
> fix(convert-formula): `_mapdata` control name must use the formula one

- bin/convert-formula.sh
---
No.
Fixes #231
Convert occurrences of `template-formula` in files related to CI.
> fix: convert more things

- .gitlab-ci.yml
- bin/convert-formula.sh
- docs/map.jinja.rst
---
No.
NA
Fix the conversion script so that reST section headings/underlines match the length of the new formula name.
NA
```
$ DEBUG=true bin/convert-formula.sh my-long_name-test
...
++ repeat_char =                                                                                                                                                                                                   
++ printf %17s                                                                                           
++ tr ' ' =                                                                                              
++ repeat_char '^'                                                                                       
++ printf %17s …
```
> fix(convert-formula.sh): fix reST underlining during conversion

- Gemfile
---
No.
This PR allows environment look in Gemfile for  ` source` and falls back to rubygems.org
> ci(proxy): allow rubygems proxy in gemfile

- TEMPLATE/libsaltcli.jinja
---
No.
Fix comments in jinja file.
> style(libsaltcli): fix comments to jinja comments

- test/integration/default/controls/packages.rb
- test/integration/default/controls/services.rb
> style: fix typo

- test/salt/pillar/default.sls
---
No.
fixing a typo in a comment string
> style(default.sls): fix minor typo

- .pre-commit-config.yaml
- .rubocop.yml
---
No.
* only run `rubocop` when relevant files have changed
test(rubocop): use `AllowedMethods` not deprecated `IgnoredMethods`
* see https://github.com/rubocop/rubocop/pull/10829
Files checked:
```
Gemfile
test/integration/default/controls/services.rb
test/integration/default/controls/config.rb
test/integration/default/controls/subcomponent_config.rb
test/integration/default/controls/_mapdata.rb
bin/kitchen
test/integration/default/controls/packages.rb
test/integration/share/libraries/system.rb
```
> test(rubocop): switch to using pre-commit's built-in file filtering 

- FORMULA
SUSE based distributions report the "os" grain as "SUSE". Only "os_family" is reported as "Suse".
---
No.
Use correct grain reference in `FORMULA` file.
> fix(suse): correct OS grain

- .gitlab-ci.yml
> ci: update `ci-pre-commit` to v2.4.10

- .gitlab-ci.yml
- kitchen.yml
- test/integration/default/files/_mapdata/almalinux-9.yaml
- test/integration/default/files/_mapdata/amazonlinux-2023.yaml
- test/integration/default/files/_mapdata/centos-9.yaml
- test/integration/default/files/_mapdata/debian-12.yaml
- test/integration/default/files/_mapdata/fedora-40.yaml
- test/integration/default/files/_mapdata/fedora-41.yaml
- test/integration/default/files/_mapdata/oraclelinux-9.yaml
- test/integration/default/files/_mapdata/rockylinux-9.yaml
- test/integration/default/files/_mapdata/ubuntu-24.yaml
---
No.
this will update the ci testing to use the latest 3006, 3007, and master container images
> ci: use latest test images

- .github/renovate.json5
- .pre-commit-config.yaml
- **ci(renovate): enable and group Pre-commit hook non-major updates**
- **chore: rename `rstcheck` hook repo**
> ci(renovate): enable and group Pre-commit hook non-major updates

- .github/renovate.json5
- .gitlab-ci.yml
- **ci(renovate): include digest updates in GitLab images group**
- **ci(renovate): improve wording**
- **ci(gitlab-ci): specify version for `dind` service image**
> ci: small CI tidy up

- .pre-commit-config.yaml
* add hook `commitlint-ci` that lints commit messages
since the last tag
> test: update `commitlint` hook to v19.8.1

- .gitlab-ci.yml
- kitchen.yml
- **ci(gitlab-ci): optimise test instance caching**
- **test(kitchen): drop timeout to `60` seconds**
> ci(gitlab-ci): optimise test instance caching

- .github/workflows/main.yml
- .yamllint
- **test(yamllint): allow for long words and Renovate-specific comments**
- **ci(workflows): add testing for some platforms to GitHub Actions**
> ci(workflows): add testing for some platforms to GitHub Actions

- .gitlab-ci.yml
* this is now handled in `commitlint.config.js`
> ci(gitlab-ci): remove amended commit due to `coqbot`
